### ISSUE TITLE
Euler angle  object not being detected 

### ISSUE THREAD

**Issue by offjangir** [mavlink/MAVSDK-Python#359]
I was trying to get Euler angels of the drone I used the following  code:

async def run():
    drone = System(mavsdk_server_address="localhost", port=(50040))
    await drone.connect()
    async for EulerAngle in drone.telemetry.EulerAngle():
        print(f"Roll: {EulerAngle.roll_deg}")
        break
if name == "main":
       loop = asyncio.get_event_loop()
       loop.run_until_complete(run())

but I am getting the following error:
Traceback (most recent call last):
  File "multimav.py", line 60, in <module>
    loop.run_until_complete(D.telemetry())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "multimav.py", line 41, in telemetry
    async for EulerAngle in drone.telemetry.EulerAngle():
AttributeError: 'Telemetry' object has no attribute 'EulerAngle'
Exception ignored in: <bound method System.__del__ of <mavsdk.system.System object at 0x7fd0241245c0>>
Traceback (most recent call last):
  File "/home/reaperj/.local/lib/python3.6/site-packages/mavsdk/system.py", line 56, in __del__

**Comment by offjangir** [comment]
Found the error.
