### ISSUE TITLE
Abstract away gRPC errors

### ISSUE THREAD

**Issue by JonasVautherin** [mavlink/MAVSDK-Python#53]
As reported in #49, the way we handle gRPC errors is not elegant (and leaking gRPC to the user.

For instance, this is the output if the backend is not reachable:

```
[ ERROR] <_Rendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "Name resolution failure"
        debug_error_string = "{"created":"@1550220055.531945000","description":"Failed to create subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":2261,"referenced_errors":[{"created":"@1550220055.531943000","description":"Name resolution failure","file":"src/core/ext/filters/client_channel/request_routing.cc","file_line":163,"grpc_status":14}]}"
>
Traceback (most recent call last):
File "/Users/docs/boulot/controleur/controleur/Autopilot.py", line 68, in connect
autopilot_type = await Autopilot.vehicle.info.get_version()
File "/Users/docs/boulot/controleur/controleur/Libs/DronecodeSDK-Python/dronecode_sdk/plugins/info.py", line 288, in get_version
response = await self._stub.GetVersion(request)
File "/Users/.local/share/virtualenvs/controleur-7At54XPt/lib/python3.6/site-packages/aiogrpc/channel.py", line 40, in __call__
return await fut
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "Name resolution failure"
        debug_error_string = "{"created":"@1550220055.531945000","description":"Failed to create subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":2261,"referenced_errors":[{"created":"@1550220055.531943000","description":"Name resolution failure","file":"src/core/ext/filters/client_channel/request_routing.cc","file_line":163,"grpc_status":14}]}"
>
```

As mentioned by @zulufoxtrot, the error can be handled with something like:

```
except grpc.RpcError as e:
logger.exception("Exception in telemetry handler: ")

if e._state.code == grpc.StatusCode.UNAVAILABLE:
logger.error("DronecodeSDK backend is unreacheable.")
```

We should probably handle that inside the SDK and raise a proper exception when that happens.

**Comment by JonasVautherin** [comment]
@zulufoxtrot: I haven't looked into the details of the `grpc.RpcError` (e.g. when that gets raised and what it means). If you have, and if you have a suggestion on how you feel we should handle that, please let me know.

One way is to fix this in one function inside one of the generated files (like `telemetry.py`), so that I can edit the auto-generation templates. Otherwise you could directly update the templates, and I could guide you for that. I am not super experienced with jinja2, so they are probably not super readable, but I'd like to improve that at some point :sweat_smile:.
