### ISSUE TITLE
takeoff and land protocol

### ISSUE THREAD

**Issue by naorwaiss** [mavlink/MAVSDK-Python#620]
i try to run takeoff and land example with cune black 
use gps and ardupilot 

```
/home/drone/.virtualenvs/pythonProject2/bin/python /tmp/pycharm_project_653/mavSDK main.py 
Waiting for drone to connect...
-- Connected to drone!
Waiting for drone to have a global position estimate...
-- Global position estimate OK
-- Arming
-- Taking off
Traceback (most recent call last):
  File "/tmp/pycharm_project_653/mavSDK main.py", line 50, in <module>
    asyncio.run(run())
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/tmp/pycharm_project_653/mavSDK main.py", line 30, in run
    await drone.action.takeoff()
  File "/home/drone/.local/lib/python3.9/site-packages/mavsdk/action.py", line 368, in takeoff
    raise ActionError(result, "takeoff()")
mavsdk.action.ActionError: COMMAND_DENIED: 'Command Denied'; origin: takeoff(); params: ()
exception calling callback for <Future at 0x7fb411d340 state=finished raised _MultiThreadedRendezvous>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/drone/.local/lib/python3.9/site-packages/aiogrpc/utils.py", line 131, in _next
    return next(self._iterator)
  File "/home/drone/.local/lib/python3.9/site-packages/grpc/_channel.py", line 541, in __next__
    return self._next()
  File "/home/drone/.local/lib/python3.9/site-packages/grpc/_channel.py", line 967, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.CANCELLED
	details = "Locally cancelled by application!"
	debug_error_string = "None"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 330, in _invoke_callbacks
    callback(self)
  File "/usr/local/lib/python3.9/asyncio/futures.py", line 398, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 796, in call_soon_threadsafe
    self._check_closed()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

the motor is start to arm but not have change at the speed of the motors... i understand that the drone didnt try to lift of 
thanks for the help 0...

**Comment by julianoes** [comment]
> `mavsdk.action.ActionError: COMMAND_DENIED: 'Command Denied'` This is what you have to investigate. I suggest subscribing to statustext messages from telemetry. They might contain some hints.

Follow up in duplicate issue https://github.com/mavlink/MAVSDK/issues/2138.
