### ISSUE TITLE
action go_to problem

### ISSUE THREAD

**Issue by naorwaiss** [mavlink/MAVSDK-Python#647]
hi, i try another way to complete my project
try to make drone with the gps position with go_to 

the goto stuck at this problem 

```
usr/bin/python3.10 /home/naor/fhsbs/drone-camera-/mavSDK main.py 
Waiting for drone to have a global position estimate...
-- Global position estimate OK
At GPS position: Latitude=47.397750699999996, Longitude=8.5456074, Altitude=488.25701904296875 meters
At cartzian position: x_i=0.0, y_i=0.0, z_i=0.0 meters
Enter the target altitude in meters: 2
-- Arming
At cartzian position: x_i=0.04447797058612646, y_i=-0.01111949242549315, z_i=2.037994384765625 meters
At cartzian position: x_i=0.04447797058612646, y_i=-0.01111949242549315, z_i=2.037994384765625 meters
Traceback (most recent call last):
  File "/home/naor/fhsbs/drone-camera-/mavSDK main.py", line 209, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/naor/fhsbs/drone-camera-/mavSDK main.py", line 198, in main
    await x_axes(15,drone)
  File "/home/naor/fhsbs/drone-camera-/mavSDK main.py", line 158, in x_axes
    await drone.action.goto_location(lat_dist, long_dist, alt_dist, yaw)
  File "/home/naor/.local/lib/python3.10/site-packages/mavsdk/action.py", line 548, in goto_location
    raise ActionError(result, "goto_location()", latitude_deg, longitude_deg, absolute_altitude_m, yaw_deg)
mavsdk.action.ActionError: UNSUPPORTED: 'Unsupported'; origin: goto_location(); params: (47.39775089999999, 8.545742698240886, 492.3330078125, 90.57073974609375)
```

its simple go to..
the simulate drone get the command of the go to but the code is collaps 
thanks for the help

**Comment by JonasVautherin** [comment]
What autopilot is that? PX4? Ardupilot? Which version of MAVSDK?
