### ISSUE TITLE
Manual control/offboard not working

### ISSUE THREAD

**Issue by mtonnberg** [mavlink/MAVSDK-Python#665]
I have tried(a lot) to remotely control my drone using MavSDK. Either there is a bug or I have missed something.
What I want to do is
* to control the drone with inputs akin to a controller. (increase thrust, pitch, yaw. etc). Or even better just to say. Go up/down/forward,strafe left, Yaw x degrees.
* To be able to increase thrust while on the ground (just as you can do with the RC).
* To be able to yaw/increase thrust/pitch/etc without gps signal

I *do not* want to use GPS-based/location aware metrics like go forward x meters.

I have tried many different things including
* the manualcontrol example found here https://github.com/mavlink/MAVSDK-Python/blob/main/examples/manual_control.py
* the offboard example found here, https://github.com/mavlink/MAVSDK-Python/blob/main/examples/offboard_velocity_body.py
* The cpp version of manual control

If I do not have my rc activated the manualcontrol-example executes without any errors but nothing happens with the propellers when the ```set_manual_control_input``` calls are made. The drone are armed (in the script) and then disarmed while the other code is executing, again without any errors (I have not understood why it is disarmed - I do not get any errors anywhere I can find.)

With the offboard examples it is a similar thing. It executes without any errors but nothing happens on the drone.

Takeoff, land and navigationbased scripts works fine.

The virtual joysticks in QGC works so I do not see why the python version would not work.

I have read some mentions of different parameters to set but I have none of these (I'm running Mateksys F406-HDTE and Ardupilot 4.4.4). For example:
[COM_RC_IN_MODE](https://docs.px4.io/v1.13/en/advanced_config/parameter_reference.html#COM_RC_IN_MODE)

Maybe there are some Px4 exclusive parameters?

My setup
```
FC, Mateksys F406-HDTE <-- serial ---> RPi Zero 2W, 64 Bookwork, Python3.9, MavSdk-Python 2.1.0 <--wifi--> pc with QGC
```
The pythonscript is executed on the RPi.

I do not get any errors if I run the mavsdk server by it self (aside from a lot of loading unknown module, but those have the debug label)

The telemetry data from the drone is perfectly healthy. I have good (20+ satellites) gps fix. The drone is calibrated and works fine when flying with the RC. 

I would like to manage to get a script that oscillates between 5% and 10% thrust (will not lift the drone but I can see/hear that the script works)

So, is this a bug or am I missing something obvious? What steps are required to be able to run the manual_control.

**Comment by julianoes** [comment]
Thanks for the issue. I think this hasn't been tested on ArduPilot. I'm not entirely sure what is missing.

Do you see the output of `mavsdk_server`, maybe that will give us a clue?

**Comment by mtonnberg** [comment]
No errors there as far as I can see but I get a lot of these debug-messages, maybe they can help us in the right direction? But I do not get any messages marked as errors.
```
....
[09:49:21|Debug] New system ID: 150 Comp ID: 64 (mavsdk_impl.cpp:737)
[09:49:21|Debug] Component Unsupported component (64) added. (system_impl.cpp:389)
[09:49:22|Debug] New system ID: 127 Comp ID: 166 (mavsdk_impl.cpp:737)
[09:49:22|Debug] Component Unsupported component (166) added. (system_impl.cpp:389)
[09:49:22|Debug] Component Unsupported component (82) added. (system_impl.cpp:389)
[09:49:22|Debug] New system ID: 159 Comp ID: 0 (mavsdk_impl.cpp:737)
[09:49:22|Debug] New system ID: 179 Comp ID: 243 (mavsdk_impl.cpp:737)
[09:49:22|Debug] Component Unsupported component (243) added. (system_impl.cpp:389)
[09:49:22|Debug] New system ID: 172 Comp ID: 129 (mavsdk_impl.cpp:737)
[09:49:22|Debug] Component Unsupported component (129) added. (system_impl.cpp:389)
[09:49:22|Debug] New system ID: 234 Comp ID: 253 (mavsdk_impl.cpp:737)
[09:49:22|Debug] Component Unsupported component (253) added. (system_impl.cpp:389)
[09:49:23|Debug] Discovered 5 component(s) (system_impl.cpp:564)
[09:49:23|Debug] New system ID: 186 Comp ID: 9 (mavsdk_impl.cpp:737)
[09:49:23|Debug] Component Unsupported component (9) added. (system_impl.cpp:389)
[09:49:23|Debug] New system ID: 45 Comp ID: 13 (mavsdk_impl.cpp:737)
[09:49:23|Debug] Component Unsupported component (13) added. (system_impl.cpp:389)
[09:49:23|Debug] New system ID: 77 Comp ID: 6 (mavsdk_impl.cpp:737)
[09:49:23|Debug] Component Unsupported component (6) added. (system_impl.cpp:389)
[09:49:24|Debug] New system ID: 225 Comp ID: 0 (mavsdk_impl.cpp:737)
[09:49:24|Debug] New system ID: 82 Comp ID: 83 (mavsdk_impl.cpp:737)
[09:49:24|Debug] Component Unsupported component (83) added. (system_impl.cpp:389)
[09:49:24|Debug] Component Unsupported component (30) added. (system_impl.cpp:389)
[09:49:24|Debug] Component Unsupported component (232) added. (system_impl.cpp:389)
[09:49:25|Debug] Component Unsupported component (60) added. (system_impl.cpp:389)
[09:49:25|Debug] Component Unsupported component (244) added. (system_impl.cpp:389)
[09:49:25|Debug] Component Unsupported component (87) added. (system_impl.cpp:389)
[09:49:25|Debug] New system ID: 16 Comp ID: 0 (mavsdk_impl.cpp:737)
[09:49:25|Debug] Component Unsupported component (112) added. (system_impl.cpp:389)
[09:49:25|Debug] Component Unsupported component (73) added. (system_impl.cpp:389)
....
```

**Comment by julianoes** [comment]
How many systems are connected? That's odd. One drone should generally be "one system" and have the same system ID.

**Comment by mtonnberg** [comment]
I have successfully removed all of the weird debug messages by explicitly setting both sysid and compid to 1. Both when I start the mavsdk-server and in the python code. However, the commands still do not work

**Comment by julianoes** [comment]
Ok good. So now the question is whether or how manual control works with ArduPilot.

**Comment by arpitpara** [comment]
will giving commands in mavproxy shell directly will help?
Try giving 'arm throttle' and 'takeoff' commands.

**Comment by mtonnberg** [comment]
Commands(like arm, takeoff, status gps_raw_int) directly in mavproxy work. Though I do not know how the Mavlink command to do manual/joystick input looks like (I've tried to find an example but haven't found any good one). If you know how the command looks like to increase the thrust to 30% for example  I can test it (without props :D ).

Also the joystick in QGC works (and QGC commmunicates over udp to the zero/mavproxy).

**Comment by mtonnberg** [comment]
About "So now the question is whether or how manual control works with ArduPilot". Do you know about any firmware for a 30x30mm stack that works better with mavsdk than Ardupilot?

**Comment by Jai-GAY** [comment]
> Try giving 'arm throttle' and 'takeoff' commands.

Pi4B Ubuntu 22.04 64-bit
Arducopter v4.2.3
[takeoff](http://mavsdk-python-docs.s3-website.eu-central-1.amazonaws.com/plugins/action.html#mavsdk.action.Action.takeoff) FAILED Action failed
Name: mavsdk
Version: 2.1.0
Summary: Python wrapper for MAVSDK
Home-page: https://github.com/mavlink/MAVSDK-Python
Author:
Author-email:
License: UNKNOWN
Location: /home/pi/.local/lib/python3.10/site-packages
Requires: aiogrpc, grpcio, protobuf
Required-by:
$

Main in
System server b4
System server done
Pi4B Waiting for drone to connect...
-- Connected to drone!
Version: [flight_sw_major: 4, flight_sw_minor: 2, flight_sw_patch: 3, flight_sw_vendor_major: 56, flight_sw_vendor_minor: 52, flight_sw_vendor_patch: 97, os_sw_major: 0, os_sw_minor: 0, os_sw_patch: 0, flight_sw_git_hash: 376130633 , os_sw_git_hash: 663466323230383 , flight_sw_version_type: RELEASE]
Flight mode: UNKNOWN
-- Arming
Arming error:  None
Battery: 9600.0
Battery_v: 16.33100128173828
Is_armed:  True
arm_event.is_set() =  True
set_takeoff_altitude:  None
Battery: 9600.0
Battery_v: 16.33500099182129
Is_armed:  True
Battery: 9600.0
Battery_v: 16.32900047302246
Is_armed:  True
**-- Taking off**
print_battery CancelledError
print_status_text CancelledError
print_altitude CancelledError
print_is_armed CancelledError
print_flight_mode CancelledError
Traceback (most recent call last):
  File "/home/pi/backup/mavsdk/mavsdk_test_20240315.py", line 214, in <module>
    asyncio.run(run())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/pi/backup/mavsdk/mavsdk_test_20240315.py", line 84, in run
    actionerr = await drone.action.takeoff()
  File "/home/pi/.local/lib/python3.10/site-packages/mavsdk/action.py", line 376, in takeoff
    raise ActionError(result, "takeoff()")
mavsdk.action.ActionError: FAILED: 'Failed'; origin: takeoff(); params: ()

**Comment by arpitpara** [comment]
In my opinion, takeoff and land only works with GPS mode, if you're working in GPS denied environment, then you should try working on Offboard mode.

**Comment by Jai-GAY** [comment]
> takeoff and land only works with GPS mode

Yes, I went out to test. the takeoff returns no error, the only problem is
**if health.is_global_position_ok and health.is_home_position_ok:** keeps failing even though MissionPlanner reports GPS healthy, Ardupilot acquired home position. I have to comment off the check for now.

Main in
System server b4
System server done
Pi4B Waiting for drone to connect...
-- Connected to drone!
Version: [flight_sw_major: 4, flight_sw_minor: 2, flight_sw_patch: 3, flight_sw_vendor_major: 56, flight_sw_vendor_minor: 52, flight_sw_vendor_patch: 97, os_sw_major: 0, os_sw_minor: 0, os_sw_patch: 0, flight_sw_git_hash: 376130633 , os_sw_git_hash: 663466323230383 , flight_sw_version_type: RELEASE]
Flight mode: LAND
Waiting for drone to have a global position estimate...
Battery: 9200.0
Battery_v: 15.653000831604004
**-- Global position state NOT good for flying.**
-- Arming
Battery: 9200.0
Battery_v: 15.672000885009766
Is_armed:  False
Is_armed:  False
Flight mode: HOLD
Arming error:  None
Status: WARNING: Terrain: clamping offset 76 to 15
Battery: 9200.0
Battery_v: 15.643000602722168
Is_armed:  True
arm_event.is_set() =  True
set_takeoff_altitude:  None
Battery: 9200.0
Battery_v: 15.646000862121582
Is_armed:  True
Battery: 9200.0
Battery_v: 15.445000648498535
Is_armed:  True
-- Taking off
Is_armed:  True
Flight mode: OFFBOARD
takeoff error:  None
Battery: 9200.0
Battery_v: 15.259000778198242
arm_event.is_set() =  True
-- Hover 10s
Is_armed:  True
Battery: 9200.0
Battery_v: 15.267001152038574
Is_armed:  True
Status: WARNING: EKF3 IMU0 MAG0 ground mag anomaly, yaw re-aligned
Status: WARNING: EKF3 IMU2 MAG0 ground mag anomaly, yaw re-aligned
Status: WARNING: EKF3 IMU1 MAG0 ground mag anomaly, yaw re-aligned
Battery: 9200.0
Battery_v: 15.320000648498535
Is_armed:  True
Battery: 9200.0
Battery_v: 15.305000305175781
Is_armed:  True
Battery: 9200.0
Battery_v: 15.334000587463379
Is_armed:  True
Battery: 9200.0
Battery_v: 15.329000473022461
Is_armed:  True
Battery: 9200.0
Battery_v: 15.313000679016113
Is_armed:  True
Battery: 9100.0
Battery_v: 15.296000480651855
Is_armed:  True
Battery: 9100.0
Battery_v: 15.292000770568848
Is_armed:  True
Battery: 9100.0
Battery_v: 15.295001029968262
Is_armed:  True
Battery: 9100.0
Battery_v: 15.295001029968262
-- Landing
Is_armed:  True
-- wait termination_task
Is_armed:  True
Flight mode: LAND
Battery: 9100.0
Battery_v: 15.348000526428223
Is_armed:  True
Battery: 9100.0
Battery_v: 15.357000350952148
Is_armed:  True
Battery: 9100.0
Battery_v: 15.330000877380371
Is_armed:  True
Battery: 9100.0
Battery_v: 15.368000984191895
Is_armed:  True
Battery: 9100.0
Battery_v: 15.4010009765625
Is_armed:  True
Battery: 9100.0
Battery_v: 15.437000274658203
Is_armed:  True
Battery: 9100.0
Battery_v: 15.43600082397461
Is_armed:  True
Battery: 9100.0
Battery_v: 15.509000778198242
print_altitude CancelledError
print_flight_mode CancelledError
-- disarm
Is_armed:  False
print_is_armed CancelledError
Battery: 9100.0
Battery_v: 15.50200080871582
Battery: 9100.0
Battery_v: 15.50300121307373
Battery: 9100.0
Battery_v: 15.647000312805176
print_status_text CancelledError
Battery: 9100.0
Battery_v: 15.653000831604004
Battery: 9100.0
Battery_v: 15.65000057220459
Battery: 9100.0
Battery_v: 15.654000282287598
print_battery CancelledError
-- run ended
Main out

**Comment by arpitpara** [comment]
Try changing mode to STABILIZED, this might help, you might have to do it again and again before running the script. Check in QGC for any errors before running.

**Comment by mtonnberg** [comment]
> In my opinion, takeoff and land only works with GPS mode, if you're working in GPS denied environment, then you should try working on Offboard mode.

I would like to run without GPS but during the current tests I do have GPS. Also, I have tried the offboard scripts as well.

**Comment by mtonnberg** [comment]
@arpitpara  @julianoes Any ideas/proposals on how I can check if it is Ardupilot that is the problem? I could flash the FC to INav instead, do you think that is a test worth doing?

**Comment by julianoes** [comment]
I would dig into whatever source code (e.g. ArduPilot) and check what's happening.
