### ISSUE TITLE
Geofence crashes with the only information being "Error"

### ISSUE THREAD

**Issue by M4ster00gway** [mavlink/MAVSDK-Python#710]
Just trying to run the example for geofence exactly as seen (not the same system address) in https://github.com/mavlink/MAVSDK-Python/blob/main/examples/geofence.py 

Throws me the following error: 

```bash
Waiting for drone to connect...
-- Connected to drone!
Fetching home location coordinates...
Uploading geofence...
Traceback (most recent call last):
  File "/home/oogway/Desktop/geofence.py", line 69, in <module>
    asyncio.run(run())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/oogway/Desktop/geofence.py", line 62, in run
    await drone.geofence.upload_geofence(geofenceData)
  File "/home/oogway/.local/lib/python3.10/site-packages/mavsdk/geofence.py", line 598, in upload_geofence
    raise GeofenceError(result, "upload_geofence()", geofence_data)
mavsdk.geofence.GeofenceError: ERROR: 'Error'; origin: upload_geofence(); params: (<mavsdk.geofence.GeofenceData object at 0x7b21850c41f0>,)
```

This has been the case ever since upgrading from mavsdk 1.4.9 before the class `GeofenceData` was implemented.

Thanks in advance for any advice!

**Comment by M4ster00gway** [comment]
Was running too old firmware on px4, updated to 1.14.3 and it works!
